---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-devops-app-deployment
  namespace: kubernetes-cluster-rajeevray
  labels:
    app: nagp-devops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-devops-app
  template:
    metadata:
      labels:
        app: nagp-devops-app
    spec:
      containers:
        - name: nagp-devops-app
          image: rajeev1189/i-rajeevray-master:latest
          ports:
            - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: nagp-devops-app-svc
  namespace: kubernetes-cluster-rajeevray
  labels:
    app: nagp-devops-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: nagp-devops-app
  type: LoadBalancer       